# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea751fa746a165445c8c8540576f549c617b3c84b793eb9040e1c5b8648a2fded34f078cd8abeb997d47146d401cfdb242f55482f65d91312e333a5717b3472a

test:
  secret_key_base: 5c07354f7717f5283443557aa0bfd5988812450ecf55d6086c83e82f978618b7338bd994f14d701b4a9c49d746edc1814d8c9bea5b55fb77317fe910d4ccdf81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
